name: Home Assistant Git Exporter (dev)
version: 0.7.4dev
slug: git-exporter
description: Export all of your Home Assistant configuration to a git repository of your choice
url: https://github.com/seb5594/Home-Assistant-git-exporter-Addon/edit/main/git-exporter
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: once
boot: manual
init: false
hassio_api: true
hassio_role: manager
map:
  - type: config
    read_only: false
  - type: all_addon_configs
    read_only: false
options:
  repository:
    url: ''
    username: ''
    password: ''
    pull_before_push: true
    commit_message: Home Assistant Git Exporter
    branch_name: main
  export:
    lovelace: true
    addons: true
    addon_configs: true
    esphome: true
    node_red: true
  check:
    enabled: true
    check_for_secrets: true
    check_for_ips: true
  exclude:
    - '*.db'
    - '*.log*'
    - __pycache__
    - ._*
    - .DS_Store
    - deps/
    - known_devices.yaml
    - tts/
    - '*.db-shm'
    - '*.db-wal'
    - '*.gz'
  secrets: []
  allowed_secrets: []
  dry_run: false
schema:
  repository:
    url: match(https://.*)
    email: match(.+@.+)?
    username: str
    password: password
    pull_before_push: bool
    commit_message: str
    branch_name: str
    ssl_verification: bool?
  export:
    lovelace: bool
    addons: bool
    addon_configs: bool
    esphome: bool
    node_red: bool
  check:
    enabled: bool
    check_for_secrets: bool
    check_for_ips: bool
  exclude:
    - str
  secrets:
    - str
  allowed_secrets:
    - str
  dry_run: bool
